### ISSUE TITLE
[Kafka] Kafka 란? & Kafka 작업 환경 세팅

### ISSUE THREAD

**Issue by robert-min** [robert-min/dev-blog#21]
## Key Problem

Kafka 란?
- 로컬 Kafka 작업환경세팅 ← docker 없이 로컬에서할 때
- docker Kafka 작업환경세팅 & docker-compose 생성
- Kafka 테스트 메세지 보내기

### Kafka 란?

- 분산 데이터 스트리밍 플랫폼
- 시스템 간의 의존성을 간접적으로 만들어 Kafka를 이용해 통신 프로토콜을 통합하기 쉬움
- 장점
    - 확장성 - 하루에 1조개의 데이터 처리가 가능, 페타바이트 데이터 처리 가능
    - 메세지 처리 속도 2ms
    - 가용성 - 클러스터 환경에서 작동
    - 분산처리, 내구성, 장애허용
- Kafka 작동원리
    - Kafka Topic : 데이터스트림이 어디어 Publish 될지 정함(파일시스템에서 폴더와 비슷한 개념?)
    - Kafka Partitions
        - 파티션마다 commit log가 쌓임
        - 파티션에 쌓인 기록은 정렬되어 있고 불변임, 모든 기록은 Offset이라는 ID를 부여받음.
    - Kafka Messages
        - Byte 배열, 카프카 메세지의 크기 제한은 없으나 가능하면 작은 크기로 유지
        - Consumer가 데이터를 받아가고 나서도 저장되지만 Retension Period 기간이 지나면  데이터는 자동으로 삭제
    - Kafka Cluster
        - 카프카 클러스터는 여러개의 카프카 브로커를 가질 수 있음
        - 카프카 토픽을 생성하면 모든 클러스터에 브로커 생성

# Kafka 란? & Kafka 작업 환경 세팅

## Intro

분산 데이터 스트리밍 플랫폼 Kafka를 사용해보자!!

 

## Key Problem

 Kafka 란?
- 로컬 Kafka 작업환경세팅 ← docker 없이 로컬에서할 때
- docker Kafka 작업환경세팅 & docker-compose 생성
- Kafka 테스트 메세지 보내기

### Kafka 란?

- 분산 데이터 스트리밍 플랫폼
- 시스템 간의 의존성을 간접적으로 만들어 Kafka를 이용해 통신 프로토콜을 통합하기 쉬움
- 장점
    - 확장성 - 하루에 1조개의 데이터 처리가 가능, 페타바이트 데이터 처리 가능
    - 메세지 처리 속도 2ms
    - 가용성 - 클러스터 환경에서 작동
    - 분산처리, 내구성, 장애허용

    
- Kafka 작동원리
    - Kafka Topic : 데이터스트림이 어디어 Publish 될지 정함(파일시스템에서 폴더와 비슷한 개념?)
    - Kafka Partitions
        - 파티션마다 commit log가 쌓임
        - 파티션에 쌓인 기록은 정렬되어 있고 불변임, 모든 기록은 Offset이라는 ID를 부여받음.
    - Kafka Messages
        - Byte 배열, 카프카 메세지의 크기 제한은 없으나 가능하면 작은 크기로 유지
        - Consumer가 데이터를 받아가고 나서도 저장되지만 Retension Period 기간이 지나면  데이터는 자동으로 삭제
    - Kafka Cluster
        - 카프카 클러스터는 여러개의 카프카 브로커를 가질 수 있음
        - 카프카 토픽을 생성하면 모든 클러스터에 브로커 생성
        - Producer가 메신저를 전송하면 Round-Robin 방식으로 파티션에 분배됨.
        - 같은 Key를 가진 message는 같은 파티션에 보내짐.
    - Kafka Producer
        - 카프카 토픽으로 메세지를 게시하는 클라이언트 어플리케이션 → 메시지를 어디 파티션에 보낼지 결정
        - 파티션 키를 지정하지않으면 Round-Robin 방식으로 파티션에 메시지 분배
        - 파티션 키를 지정하면 같은 파티션으로 분배
    - Kafka Consumer
        - Consumer Group 은 모든 파티션으로부터 데이터를 받을 수 있음
        - Consumer Group을 지정하지 않으면 새로운 Group으로 지정, 같은 그룹 내의 Consumer은 같은 파티션으로부터 동시에 데이터를 받을 수 없음.
        - Consumer은 지정된 파티션으로부터 데이터를 받을 수 있음
    - Kafka Zookeeper
        - 분산 시스템간의 정보 공유, 상태체크 서버 동기화
        - 클러스터, Topic, 파티션 리더 관리

### 로컬 Kafka 작업환경세팅 ← docker 없이 로컬에서할 때

- [https://kafka.apache.org/downloads](https://kafka.apache.org/downloads)
- 위의 사이트에서 다운로드 파일 압축해제위 home 디렉토리로 이동
- 터미널에서 kafka 폴더에서 zookeper, kafka server 실행

```bash
# shell 파일 실행할 때 config 안에 있는 properties를 함께 실행
$ ./bin/zookeeper-server-start.sh -daemon config/zookeeper.properties

$ ./bin/kafka-server-start.sh -daemon ./config/server.properties
```

- kafka topic을 생성하여 제대로 설치되었는지 확인

```bash
$ bin/kafka-topics.sh --create --bootstrap-server localhost:9092 --topic first-topic --partitions 1 --replication-factor 1
```

- python 코드로 카프카 실행할 때 kafka-python 설치 필요

```bash
$ pip install kafka-python
```

### docker Kafka 작업환경세팅 & docker-compose 생성

- Kafka Producer, consumer, cluster을 효과적으로 관리하기위해 docker를 사용
- [https://docs.docker.com/get-docker/](https://docs.docker.com/get-docker/)
- 위 사이트에서 설치 진행
- docker-compose
    - 다중 컨테이너 어플리케이션을 정의하고 공유할 수 있도록 개발된 도구
    - yml 파일로 작성
- docker-compose.yml
    - 기본 구조 : 버전 - 서비스 (컨테이너 이미지 정의)
    - 밑의 예제는 zookeeper, kafka 3 컨테이너, kafdrop(kafka를 UI로 작업할 수 있는 도구) 이미지 사용
    - 필요에따라 depends_on : 의존성을 두어 컨테이너 별로 실행 순서를 지정(kafka는 zookeeper가 실행된 후 실행되어야하고 kafdrop은 모든 kafka 컨테이너가 실행된 후에 실행되어야 함!!)

```yaml
version: '3'
services:
  zookeeper:
    image: zookeeper:3.7
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
    volumes:
      - ./data/zookeeper/data:/data
      - ./data/zookeeper/datalog:/datalogco
  kafka1:
    image: confluentinc/cp-kafka:7.0.0
    hostname: kafka1
    ports:
      - "9091:9091"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19091,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./data/kafka1/data:/tmp/kafka-logs
    depends_on:
      - zookeeper
  kafka2:
    image: confluentinc/cp-kafka:7.0.0
    hostname: kafka2
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka2:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./data/kafka2/data:/tmp/kafka-logs
    depends_on:
      - zookeeper
  kafka3:
    image: confluentinc/cp-kafka:7.0.0
    hostname: kafka3
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka3:19093,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./data/kafka3/data:/tmp/kafka-logs
    depends_on:
      - zookeeper
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKER_CONNECT: "kafka1:19091"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
```

### Kafka 테스트 메세지 보내기

- docker-compose.yml 경로에 위치한 터미널에서 docker-compose 실행

```bash
$ docker-compose up

# (참고) 실행이 제대로 되지 않거나 다시 실행하기 위해서 실행중인 docker 제거하는 명령
$ docker-compose rm -svf

# (참고) 실행 중에 이미 사용중인 포트가 있는 경우 강제로 해당 포트 제거
$ lsof -i :[포트번호]    # PID 번호 확인
$ kill -9 [PID]
```

- [[localhost:9000](http://localhost:9000/)](http://localhost:9000) 접속후 kafdrop 실행 확인 → 환경에따라 kafdrop 시간이 걸림(인내심가지고 기다리기!!)

- Topic 생성
    - (방법1) 왼쪽 하단 Topics 밑에 New 클릭 후 Topic 생성
        
       ![image](https://user-images.githubusercontent.com/91866763/229271796-9fb69b7f-eac4-4ce0-ace2-c40f8ce75079.png)
        
    - (방법2) 터미널에서 명렁어 입력
    
    ```bash
    $ bin/kafka-topics.sh --create --bootstrap-server localhost:9091 --topic test-topic --partitions 2 --replication-factor 1
    ```
    

- Topic 생성 Producer 와 Consumer 파일 생성
    - test_producer.py
    
    ```bash
    from kafka import KafkaProducer
    
    # broker 지정(도커 카프카 컨테이너로 지정한 포터로)
    brokers = ["localhost:9091", "localhost:9092", "localhost:9093"]
    topicName = "test-topic"
    
    producer = KafkaProducer(bootstrap_servers = brokers)
    
    producer.send(topicName, b"test message")
    producer.flush()
    ```
    
    - test_consumer.py
    
    ```bash
    from kafka import KafkaConsumer
    
    brokers = ["localhost:9091", "localhost:9092", "localhost:9093"]
    consumer = KafkaConsumer("test-topic", bootstrap_servers=brokers)
    
    for message in consumer:
        print(message)
    ```
    
- 터미널에서 각각 해당 파일 실행
    - 메세지를 받을 consumer 실행
    
    ```bash
    $ python test_consumer.py
    ```
    
    - 메세지를 보낼 producer 실행
    
    ```bash
    $ python test_producer.py
    ```
    
    - consumer을 실행한 터미널에서 메세지 확인
    
   ![image](https://user-images.githubusercontent.com/91866763/229271831-8f7ffae9-1d32-4a06-ae77-3bb129599d56.png)
    
- Kafdrop에서 메세지 전달내역 확인
![image](https://user-images.githubusercontent.com/91866763/229271850-e227c564-dccc-409f-9ee8-c1f1e4ae7c9e.png)
