### ISSUE TITLE
[Kafka] Kafka를 활용한 비정상 데이터 탐지

### ISSUE THREAD

**Issue by robert-min** [robert-min/dev-blog#22]
## Intro

Kafka를 활용하여 비정상, 정상 데이터를 구분하는 데이터 파이프라인을 만들어보자

## Key Problem

 - 로컬 환경에서 Kafka 기본 환경 세팅
- Kafka 사용을 위해 Topic 생성
- Kafka-python으로 테스트 코드 작성
- 비정상 데이터 탐지 테스트

### 로컬 환경에서 Kafka 기본 환경 세팅

- [https://kafka.apache.org/downloads](https://kafka.apache.org/downloads)
- 위 사이트에 다운로드 받은 파일 중 bin 폴더에 있는 kafka-server 터미널에서 실행 → [[server.properties](http://server.properties/)](http://server.properties) 파일과 함께 클릭

```bash
# 파일을 저장한 곳에 따라 코드가 달라질 수 있음
$ ./bin/kafka-server-start.sh -daemon ./config/server.properties
```

- 파이썬으로 Kafka를 사용하기 위해 kafka-python 설치

```bash
$ pip install kafka-python
```

- docker-compose.yml 파일 실행

```yaml
version: '3'
services:
  zookeeper:
    image: zookeeper:3.7
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
    volumes:
      - ./data/zookeeper/data:/data
      - ./data/zookeeper/datalog:/datalogco
  kafka1:
    image: confluentinc/cp-kafka:7.0.0
    hostname: kafka1
    ports:
      - "9091:9091"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19091,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./data/kafka1/data:/tmp/kafka-logs
    depends_on:
      - zookeeper
  kafka2:
    image: confluentinc/cp-kafka:7.0.0
    hostname: kafka2
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka2:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./data/kafka2/data:/tmp/kafka-logs
    depends_on:
      - zookeeper
  kafka3:
    image: confluentinc/cp-kafka:7.0.0
    hostname: kafka3
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka3:19093,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./data/kafka3/data:/tmp/kafka-logs
    depends_on:
      - zookeeper
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKER_CONNECT: "kafka1:19091"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
```

```bash
# 터미널에서 실행
$ docker-compose up
```

### Kafka 사용을 위해 Topic 생성

- [[localhost:9000](http://localhost:9000/)](http://localhost:9000) 에 접속하여 New 버튼 클릭 후 Topic 생성 → Kafdrop UI로 작업
    - payments, fraud_payments, legit_payments 3개 Topic 생성

![image](https://user-images.githubusercontent.com/91866763/229271959-46d8cce0-9c40-41b0-a073-c7365cb5d468.png)

### Kafka-python으로 테스트 코드 작성

- payment_producer.py → 임의로 생성한 데이터를 보내주는 파일

```python
from kafka import KafkaProducer
import datetime
import pytz
import time
import random
import json

TOPIC_NAME = "payments"
brokers = ["localhost:9091", "localhost:9092", "localhost:9093"]
producer = KafkaProducer(bootstrap_servers=brokers)

# 시간 데이터 생성
def get_time_date():
    utc_now = pytz.utc.localize(datetime.datetime.utcnow())
    kst_now = utc_now.astimezone(pytz.timezone("Asia/Seoul"))
    d = kst_now.strftime("%m/%d/%Y")
    t = kst_now.strftime("%H:%M:%S")
    return d, t

# payment 데이터 생성
def generate_payment_data():
    payment_type = random.choice(["VISA", "MASTER", "BITCOIN"])
    amount = random.randint(0, 100)
    to = random.choice(["me", "mom", "sister", "brother", "stranger"])
    return payment_type, amount, to

# 데이터 전달
while True:
    d, t = get_time_date()
    payment_type, amount, to = generate_payment_data()
    new_data = {
        "DATE": d,
        "TIME": t,
        "PAYMENT_TYPE": payment_type,
        "AMOUNT": amount,
        "TO": to
    }

    producer.send(TOPIC_NAME, json.dumps(new_data).encode("utf-8"))
    print(new_data)
    time.sleep(1)
```

- fraud_detector.py → payment로 부터 받은 데이터가 정상인지 비정상인지 판단하는 파일

```python
from kafka import KafkaConsumer, KafkaProducer
import json

# Kafka Topic
PAYMENT_TOPIC = "payments"
FRAUD_TOPIC = "fraud_payments"
LEGIT_TOPIC = "legit_payments"

brokers = ["localhost:9091", "localhost:9092", "localhost:9093"]

consumer = KafkaConsumer(PAYMENT_TOPIC, bootstrap_servers=brokers)
producer = KafkaProducer(bootstrap_servers=brokers)

# PAYMENT_TYPE = BITCOIN 구분
def is_suspicious(transactions):
    if transactions["PAYMENT_TYPE"] == "BITCOIN":
        return True
    return False

# 구분한 데이터 전달
for message in consumer:
    msg = json.loads(message.value.decode())
    topic = FRAUD_TOPIC if is_suspicious(msg) else LEGIT_TOPIC
    producer.send(topic, json.dumps(msg).encode("utf-8"))
    print(topic, is_suspicious(msg), msg["PAYMENT_TYPE"])
```

- fraud_processor.py → 비정상으로 분류된 데이터를 받아 처리하는 파일

```python
from kafka import KafkaConsumer
import json

FRAUD_TOPIC = "fraud_payments"

brokers = ["localhost:9091", "localhost:9092", "localhost:9093"]

consumer = KafkaConsumer(FRAUD_TOPIC, bootstrap_servers=brokers)

for message in consumer:
    msg = json.loads(message.value.decode())
    to = msg["TO"]
    amount = msg["AMOUNT"]
    if msg["TO"] == "stranger":
        print(f"[ALERT] fraud detected payment to : {to} - {amount}")
    else:
        print(f"[PREPROCESSING BITCOIN] payment to : {to} - {amount}")
```

- legit_processor.py → 정상으로 분류된 데이터를 받아 처리하는 파일

```python
from kafka import KafkaConsumer
import json

LEGIT_TOPIC = "legit_payments"
brokers = ["localhost:9091", "localhost:9092", "localhost:9093"]

consumer = KafkaConsumer(LEGIT_TOPIC, bootstrap_servers=brokers)

for message in consumer:
    msg = json.loads(message.value.decode())
    to = msg["TO"]
    amount = msg["AMOUNT"]
    if msg["PAYMENT_TYPE"] == "VISA":
        print(f"[VISA] payment to : {to} - {amount}")
    elif msg["PAYMENT_TYPE"] == "MASTER":
        print(f"[MASTER] payment to : {to} - {amount}")
    else:
        print("unable to process")
```

### 비정상 데이터 탐지 테스트

- 작성한 코드 터미널 테스트 진행 → 설계한 데이터 파이프라인대로 진행 확인
![image](https://user-images.githubusercontent.com/91866763/229271969-5507fcdb-5db4-4cf7-a08f-555fd862ff51.png)
