### ISSUE TITLE
[Hadoop-k8s] Hadoop on k8s 구축 - (2) hadoop.yaml

### ISSUE THREAD

**Issue by robert-min** [robert-min/dev-blog#36]
## Intro

하둡 쿠버네티스 배포를 위해 작성한 YAML 파일 정리한 글입니다.

작성된 파일은 앞서 작성한 Dockerfile을 기반으로 작성되었습니다.

해당 내용은 코드 정리만 해놓은 페이지로 별도의 설명은 없습니다.

## Key Problem
- namenode
- datanode
- Resourcemanager
- Nodemanager
- historyserver
- storage.yaml

### namenode

```yaml
# hadoop.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: namenode
spec:
  serviceName: namenode
  replicas: 1
  selector:
    matchLabels:
      app: namenode

  template:
    metadata:
      labels:
        app: namenode
    spec:
      containers:
      - name: namenode
        image: robertmin/namenode:default
        imagePullPolicy: Always
        env:
        - name: CLUSTER_NAME
          value: test
        volumeMounts:
        - mountPath: /hadoop/dfs/name
          name: hadoop-namenode-storage
        ports:
        - containerPort: 9000
        - containerPort: 9870
      volumes:
      - name: hadoop-namenode-storage
        persistentVolumeClaim:
          claimName: hadoop-namenode-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: namenode-web

spec:
  selector:
    app: namenode
  ports:
  - name: http
    protocol: TCP
    port: 9870
    nodePort: 30080

  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: namenode-0

spec:
  type: ClusterIP
  selector:
    app: namenode
  ports:
  - name: nn-ip-1
    protocol: TCP
    port: 9000
  - name: nn-ip-2
    protocol: TCP
    port: 9870

  

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hadoop-namenode-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "default1a"
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
```

### datanode

```yaml
## hadoop.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: datanode

spec:
  serviceName: datanode
  replicas: 1
  selector:
    matchLabels:
      app: datanode
  template:
    metadata:
      labels:
        app: datanode
    spec:
      containers:
      - name: datanode
        image: robertmin/datanode:default
        imagePullPolicy: Always
        env:
        - name: SERVICE_PRECONDITION
          value: "namenode-0:9870"
        volumeMounts:
        - name: hadoop-datanode-storage
          mountPath: /hadoop/dfs/data
        ports:
        - containerPort: 10019
      volumes:
      - name: hadoop-datanode-storage
        persistentVolumeClaim:
          claimName: hadoop-datanode-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: datanode-0
spec:
  type: ClusterIP
  selector:
    app: datanode
  ports:
  - name: dn-ip
    protocol: TCP
    port: 10019

---
apiVersion: v1
kind: Service
metadata:
  name: datanode-web

spec:
  selector:
    app: datanode
  ports:
  - name: http
    protocol: TCP
    port: 10022
    nodePort: 30022

  type: NodePort

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hadoop-datanode-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "default1a"
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 120Gi
```

### Resourcemanager

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: resourcemanager

spec:
  serviceName: resourcemanager
  replicas: 1
  selector:
    matchLabels:
      app: resourcemanager
  template:
    metadata:
      labels:
        app: resourcemanager
    spec:
      containers:
      - name: resourcemanager
        image: robertmin/resourcemanager:default
        imagePullPolicy: Always
        # resources:
        #   requests:
        #     memory: "2Gi"
        #     cpu: "4000m"
        #   limits:
        #     memory: "4Gi"
        #     cpu: "10000m" 
        env:
        - name: SERVICE_PRECONDITION
          value: "namenode-0:9870 datanode-0:10022"
        volumeMounts:
        - mountPath: /hadoop/dfs/name
          name: hadoop-rm-storage
        ports:
        - containerPort: 8088
      volumes:
      - name: hadoop-rm-storage
        persistentVolumeClaim:
          claimName: hadoop-rm-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: resourcemanager-web

spec:
  selector:
    app: resourcemanager
  ports:
  - name: http
    protocol: TCP
    port: 8088
    nodePort: 30090

  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: resourcemanager-0

spec:
  type: ClusterIP
  selector:
    app: resourcemanager
  ports:
  - name: rm-ip-1
    protocol: TCP
    port: 8030
  - name: rm-ip-2
    protocol: TCP
    port: 8033
  - name: rm-ip-3
    protocol: TCP
    port: 8032

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hadoop-rm-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "default1a"
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
```

### Nodemanager

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nodemanager
spec:
  serviceName: nodemanager
  replicas: 1
  selector:
    matchLabels:
      app: nodemanager

  template:
    metadata:
      labels:
        app: nodemanager
    spec:
      containers:
      - name: nodemanager
        image: robertmin/nodemanager:default
        imagePullPolicy: Always
        env:
        - name: SERVICE_PRECONDITION
          value: "namenode-0:9870 datanode-0:10022 resourcemanager-8088"
        volumeMounts:
        - mountPath: /hadoop/dfs/name
          name: nodemanager-storage
        ports:
        - containerPort: 8042
      volumes:
      - name: nodemanager-storage
        persistentVolumeClaim:
          claimName: hadoop-nodemanager-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: nodemanager-0

spec:
  type: ClusterIP
  selector:
    app: nodemanager
  ports:
  - name: nm-ip-1
    protocol: TCP
    port: 8042

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hadoop-nodemanager-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "default1a"
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
```

### historyserver

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: historyserver

spec:
  serviceName: historyserver
  replicas: 1
  selector:
    matchLabels:
      app: historyserver
  template:
    metadata:
      labels:
        app: historyserver
    spec:
      containers:
      - name: historyserver
        image: robertmin/historyserver:default
        imagePullPolicy: Always
        # env:
        # - name: SERVICE_PRECONDITION
        #   value: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
        volumeMounts:
        - mountPath: /hadoop/yarn/timeline
          name: hadoop-hs-storage
        ports:
        - containerPort: 8188
      volumes:
      - name: hadoop-hs-storage
        persistentVolumeClaim:
          claimName: hadoop-hs-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: historyserver-0

spec:
  selector:
    app: historyserver
  ports:
  - name: http
    protocol: TCP
    port: 8188
    nodePort: 30100

  type: NodePort

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hadoop-hs-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "default1a"
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
```

### storage.yaml
```yaml
## storage.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default1a
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zone: ap-northeast-3a
  iopsPerGB: "10"
```
