### ISSUE TITLE
[Hadoop-k8s] Hadoop on k8s 구축 - (3) hive.yaml & Hbase.yaml

### ISSUE THREAD

**Issue by robert-min** [robert-min/dev-blog#37]
## Intro

하둡 쿠버네티스 배포를 위해 작성한 YAML 파일 정리한 글입니다.

작성된 파일은 앞서 작성한 Dockerfile을 기반으로 작성되었습니다.

해당 내용은 코드 정리만 해놓은 페이지로 별도의 설명은 없습니다.

## Key Problem

 - hive.yaml
- hbase.yaml
- zookeeper.yaml

### hive.yaml

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-server

spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-server
  template:
    metadata:
      labels:
        app: hive-server
    spec:
      containers:
      - name: hive-server
        image: robertmin/hive_base:default
        imagePullPolicy: Always
        env:
        - name: SERVICE_PRECONDITION
          value: "hive-metastore:9083"
        ports:
        - containerPort: 10000
        - containerPort: 10002
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"

---
apiVersion: v1
kind: Service
metadata:
  name: hive-server

spec:
  type: ClusterIP
  selector:
    app: hive-server
  ports:
  - name: hive-ip-1
    protocol: TCP
    port: 10000
  - name: hive-ip-2
    protocol: TCP
    port: 10002

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore

spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
      - name: hive-metastore
        image: robertmin/hive_base:default
        imagePullPolicy: Always
        # env:
        # - name: SERVICE_PRECONDITION
        #   value: "namenode:9870 datanode:9864 hive-metastore-postgresql:5432"
        ports:
        - containerPort: 9083
        command: ["/bin/bash"]
        args: ["-c", "/opt/hive/bin/hive --service metastore"]
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"

---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore

spec:
  type: ClusterIP
  selector:
    app: hive-metastore
  ports:
  - name: hive-metastore-ip-1
    protocol: TCP
    port: 9083

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hive-metastore-postgre
spec:
  serviceName: hive-metastore-postgresql
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore-postgresql
  template:
    metadata:
      labels:
        app: hive-metastore-postgresql
    spec:
      containers:
      - name: hive-metastore-postgresql
        image: robertmin/postgre:hive
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
      volumes:
      - name: hive-metastore-storage
        persistentVolumeClaim:
          claimName: hive-metastore-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore-postgresql

spec:
  type: ClusterIP
  selector:
    app: hive-metastore-postgresql
  ports:
  - name: postgre-ip-1
    protocol: TCP
    port: 5432

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hive-metastore-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "default1a"
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
# presto
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: presto-coordinator
spec:
  serviceName: presto-coordinator
  replicas: 1
  selector:
    matchLabels:
      app: presto-coordinator
  template:
    metadata:
      labels:
        app: presto-coordinator
    spec:
      containers:
      - name: presto-coordinator
        image: shawnzhu/prestodb:0.181
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      volumes:
      - name: presto-coordinator-storage
        persistentVolumeClaim:
          claimName: presto-coordinator-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: presto-coordinator

spec:
  type: ClusterIP
  selector:
    app: presto-coordinator
  ports:
  - name: presto-ip-1
    protocol: TCP
    port: 8080

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: presto-coordinator-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "default1a"
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```

### hbase.yaml

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hbase-master
spec:
  serviceName: hbase-master
  replicas: 1
  selector:
    matchLabels:
      app: hbase-master
  template:
    metadata:
      labels:
        app: hbase-master
    spec:
      containers:
      - name: hbase-master
        image: robertmin/hbase_master:default
        imagePullPolicy: Always
        env:
        - name: SERVICE_PRECONDITION
          value: "namenode-0:9870 datanode-0:10022 zoo:2181"
        ports:
        - containerPort: 16000
        - containerPort: 16010
      volumes:
      - name: hbase-master-storage
        persistentVolumeClaim:
          claimName: hbase-master-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: hbase-master-0

spec:
  type: ClusterIP
  selector:
    app: hbase-master
  ports:
  - name: hbase-master-ip-1
    protocol: TCP
    port: 16000
  - name: hbase-master-ip-2
    protocol: TCP
    port: 16010

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hbase-master-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "default1a"
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hbase-region
spec:
  serviceName: hbase-region
  replicas: 1
  selector:
    matchLabels:
      app: hbase-region
  template:
    metadata:
      labels:
        app: hbase-region
    spec:
      containers:
      - name: hbase-region
        image: robertmin/hbase_server:default
        imagePullPolicy: Always
        env:
        - name: SERVICE_PRECONDITION
          value: "namenode-0:9870 datanode-0:10022 zoo:2181 hbase-master:16010"
        ports:
        - containerPort: 16000
        - containerPort: 16010
      volumes:
      - name: hbase-region-storage
        persistentVolumeClaim:
          claimName: hbase-region-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: hbase-region-0

spec:
  type: ClusterIP
  selector:
    app: hbase-region
  ports:
  - name: hbase-region-ip-1
    protocol: TCP
    port: 16020
  - name: hbase-region-ip-2
    protocol: TCP
    port: 16030

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hbase-region-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "default1a"
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```

### zookeeper.yaml

- kubernetes 문서에서 제공하는 yaml 파일 사용
```yaml
apiVersion: v1
kind: Service
metadata:
  name: zoo
  labels:
    app: zoo
spec:
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  - port: 2181
    name: client
  clusterIP: None
  selector:
    app: zoo

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zoo
spec:
  selector:
    matchLabels:
      app: zoo
  serviceName: zoo
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: zoo
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - zoo
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: kubernetes-zookeeper
        imagePullPolicy: Always
        image: "k8s.gcr.io/kubernetes-zookeeper:1.0-3.4.10"
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        command:
        - sh
        - -c
        - "start-zookeeper \
          --servers=3 \
          --data_dir=/var/lib/zookeeper/data \
          --data_log_dir=/var/lib/zookeeper/data/log \
          --conf_dir=/opt/zookeeper/conf \
          --client_port=2181 \
          --election_port=3888 \
          --server_port=2888 \
          --tick_time=2000 \
          --init_limit=10 \
          --sync_limit=5 \
          --heap=512M \
          --max_client_cnxns=60 \
          --snap_retain_count=3 \
          --purge_interval=12 \
          --max_session_timeout=40000 \
          --min_session_timeout=4000 \
          --log_level=INFO"
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "zookeeper-ready 2181"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "zookeeper-ready 2181"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/zookeeper
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi

```
